# Rules

disabled_rules:
  - todo

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - file_header
  - file_name
  - file_name_no_space
  - identical_operands
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_zero_over_explicit_init
  - sorted_imports
  - static_operator
  - toggle_bool
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Locations

included:
  - Sources
  - Tests

# Rule Customizations

cyclomatic_complexity:
  ignores_case_statements: true

file_header:
  forbidden_pattern: "[^\n]"

identifier_name:
  excluded:
    - id

trailing_comma:
  mandatory_comma: true

type_contents_order:
  order:
  - case
  - type_alias
  - associated_type
  - type_property
  - instance_property
  - ib_inspectable
  - ib_outlet
  - initializer
  - deinitializer
  - type_method
  - view_life_cycle_method
  - ib_action
  - other_method
  - subscript
  - subtype

# Custom Rules

custom_rules:
  attribute_with_parameter:
    severity: warning
    regex: "@\\w*\\([^\\n]*\\)[^\\n]+"
    name: "Attribute with Parameter"
    message: "Attributes with parameters should be on their own line"

  attribute_without_parameter:
    severity: warning
    regex: "@\\w*\\n"
    name: "Attribute without Parameters"
    message: "Attributes without parameters should be on the same line as declaration"
