name: Open PR

on:
  pull_request:

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Lint
        run: swiftlint

  unit_tests:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Build for macOS
        run: swift build -v

      - name: Run macOS tests
        run: swift test -v

      - name: Build for iOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme IndexedDataStore -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty

      - name: Run iOS tests
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme IndexedDataStore -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
